theme: jekyll-theme-architect
title: [Alex Pardus | Mechanical Design Engineer]
description: [I created this site to keep a log of the projects I have worked on and showcase my work to those who are interested. Please don't hesitate to reach out with questions!] 
